# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("deal_created", "Negócio criado"),
                    ("deal_stage_changed", "Negócio mudou de etapa"),
                    ("company_created", "Empresa criada"),
                    ("contact_created", "Contato criado"),
                    ("contact_stage_changed", "Contato mudou de estágio"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("deal_created", "Negócio criado"),
                    ("deal_stage_changed", "Negócio mudou de etapa"),
                    ("company_created", "Empresa criada"),
                    ("contact_created", "Contato criado"),
                    ("contact_stage_changed", "Contato mudou de estágio"),
                ],
                max_length=40,
                verbose_name="Gatilho",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="condition_stage",
            field=models.CharField(blank=True, max_length=20, verbose_name="Etapa/coluna (condição)"),
        ),
        migrations.AlterField(
            model_name="automation",
            name="action",
            field=models.CharField(
                choices=[
                    ("create_task", "Criar tarefa"),
                    ("create_note", "Adicionar nota"),
                    ("create_deal", "Criar negócio"),
                    ("move_deal", "Mover negócio"),
                    ("set_contact_stage", "Atualizar estágio do contato"),
                ],
                default="create_task",
                max_length=20,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="automation",
            name="action_text",
            field=models.CharField(blank=True, max_length=300, verbose_name="Texto"),
        ),
        migrations.AddField(
            model_name="automation",
            name="conditions",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="automation",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
