# Generated by Django 6.0.7 on 2026-07-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('company', 'Empresas'), ('contact', 'Contatos'), ('deal', 'Negócios')], max_length=20)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=80, verbose_name='Rótulo')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto longo'), ('number', 'Número'), ('date', 'Data'), ('select', 'Seleção'), ('checkbox', 'Sim/Não')], default='text', max_length=12, verbose_name='Tipo')),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'ordering': ['object_type', 'order', 'id'],
                'unique_together': {('workspace', 'object_type', 'key')},
            },
        ),
    ]
