# Generated by Django 6.0.7 on 2026-07-14 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('trigger', models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado')], max_length=40, verbose_name='Gatilho')),
                ('condition_stage', models.CharField(blank=True, max_length=20, verbose_name='Etapa (condição)')),
                ('action', models.CharField(choices=[('create_task', 'Criar tarefa'), ('create_note', 'Adicionar nota')], default='create_task', max_length=20, verbose_name='Ação')),
                ('action_text', models.CharField(max_length=300, verbose_name='Texto')),
                ('action_due_days', models.PositiveIntegerField(default=2, verbose_name='Prazo (dias)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado')], max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
