# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_automation_flow_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="automation",
            name="canvas",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
