# Generated by Django 6.0.7 on 2026-07-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_automation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='brand_color',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Cor da marca'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
