# Generated by Django 6.0.7 on 2026-07-14 14:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workspace_brand_color_workspace_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.workspace_logo_path, verbose_name='Logo'),
        ),
    ]
