# Generated by Django 6.0.7 on 2026-07-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_automationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='action',
            field=models.CharField(choices=[('create_task', 'Criar tarefa'), ('create_note', 'Adicionar nota'), ('create_deal', 'Criar negócio'), ('move_deal', 'Mover negócio'), ('set_contact_stage', 'Atualizar estágio do contato'), ('set_custom_field', 'Atualizar campo'), ('delay', 'Aguardar'), ('send_webhook', 'Enviar webhook')], default='create_task', max_length=20, verbose_name='Ação'),
        ),
    ]
