# Generated by Django 6.0.7 on 2026-07-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_automation_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='resume_node_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationrun',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
