# Generated by Django 6.0.7 on 2026-07-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_automationrun_resume_node_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='icon',
            field=models.CharField(choices=[('bolt', 'Raio'), ('clock', 'Tempo'), ('pipeline', 'Pipeline'), ('users', 'Contatos'), ('command', 'Integracao'), ('sliders', 'Filtro'), ('check', 'Regra'), ('hash', 'Campo')], default='bolt', max_length=24, verbose_name='Ícone'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='action',
            field=models.CharField(choices=[('create_task', 'Criar tarefa'), ('create_note', 'Adicionar nota'), ('create_deal', 'Criar negócio'), ('move_deal', 'Mover negócio'), ('set_contact_stage', 'Atualizar estágio do contato'), ('set_custom_field', 'Atualizar campo'), ('delay', 'Aguardar'), ('send_webhook', 'Enviar webhook'), ('http_request', 'HTTP request')], default='create_task', max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Agendamento recorrente'), ('webhook_received', 'Webhook recebido')], max_length=40, verbose_name='Gatilho'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Agendamento recorrente'), ('webhook_received', 'Webhook recebido')], max_length=40),
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('facebook', 'Facebook Lead Ads'), ('instagram', 'Instagram'), ('forms', 'Forms nativos'), ('whatsapp', 'WhatsApp'), ('webhook', 'Webhooks'), ('api', 'API / HTTP')], max_length=24)),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('disconnected', 'Desconectada'), ('connected', 'Conectada')], default='disconnected', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
                'ordering': ['provider'],
                'unique_together': {('workspace', 'provider')},
            },
        ),
    ]
