# Generated by Django 6.0.7 on 2026-07-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_automation_trigger_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Schedule trigger'), ('webhook_received', 'Webhook recebido')], max_length=40, verbose_name='Gatilho'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Schedule trigger'), ('webhook_received', 'Webhook recebido')], max_length=40),
        ),
    ]
