# Generated by Django 6.0.7 on 2026-07-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_automation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('textarea', 'Texto longo'), ('number', 'Número'), ('date', 'Data'), ('select', 'Lista (uma opção)'), ('multiselect', 'Múltipla escolha'), ('checkbox', 'Sim/Não')], default='text', max_length=12, verbose_name='Tipo'),
        ),
    ]
