# Generated by Django 6.0.7 on 2026-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Schedule trigger'), ('webhook_received', 'Webhook recebido'), ('facebook_lead', 'Lead do Facebook')], max_length=40, verbose_name='Gatilho'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('deal_created', 'Negócio criado'), ('deal_stage_changed', 'Negócio mudou de etapa'), ('company_created', 'Empresa criada'), ('contact_created', 'Contato criado'), ('contact_stage_changed', 'Contato mudou de estágio'), ('schedule_interval', 'Schedule trigger'), ('webhook_received', 'Webhook recebido'), ('facebook_lead', 'Lead do Facebook')], max_length=40),
        ),
    ]
