# Generated by Django 6.0.6 on 2026-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_automation_trigger_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('workspace', 'event_type', 'source_key'), name='unique_event_source_key'),
        ),
    ]
