# Generated by Django 6.0.7 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_source_key_event_unique_event_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='sidebar_theme',
            field=models.CharField(choices=[('light', 'Clara'), ('dark', 'Escura')], default='light', max_length=10, verbose_name='Menu lateral'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ui_radius',
            field=models.CharField(choices=[('rounded', 'Arredondado'), ('soft', 'Suave'), ('sharp', 'Reto')], default='rounded', max_length=10, verbose_name='Cantos'),
        ),
    ]
