# Generated by Django 6.0.7 on 2026-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workspace_sidebar_theme_workspace_ui_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='logo_data',
            field=models.TextField(blank=True, default='', verbose_name='Logo (dados)'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ui_font',
            field=models.CharField(choices=[('sans', 'Padrão'), ('serif', 'Serifada')], default='sans', max_length=10, verbose_name='Fonte'),
        ),
    ]
