# Generated by Django 6.0.7 on 2026-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workspace_logo_data_workspace_ui_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='app_theme',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10, verbose_name='Tema do app'),
        ),
    ]
