# Generated by Django 6.0.7 on 2026-07-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workspace_app_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='currency',
            field=models.CharField(choices=[('BRL', 'Real (R$)'), ('USD', 'Dólar (US$)'), ('EUR', 'Euro (€)')], default='BRL', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='date_format',
            field=models.CharField(choices=[('dmy', 'dd/mm/aaaa'), ('mdy', 'mm/dd/aaaa')], default='dmy', max_length=4, verbose_name='Formato de data'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='ui_font',
            field=models.CharField(choices=[('sans', 'Padrão'), ('serif', 'Serifada'), ('rounded', 'Arredondada'), ('mono', 'Técnica')], default='sans', max_length=10, verbose_name='Fonte'),
        ),
    ]
