# Generated by Django 6.0.7 on 2026-07-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_workspace_currency_workspace_date_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='dashboard_layout',
            field=models.JSONField(blank=True, default=list, verbose_name='Painel'),
        ),
    ]
