# Generated by Django 6.0.7 on 2026-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_workspace_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='retention_months',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Retenção (meses)'),
        ),
    ]
