# Generated by Django 6.0.7 on 2026-07-25 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workspace_retention_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='suspended',
            field=models.BooleanField(default=False, verbose_name='Suspenso'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='suspended_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', 'Admin da plataforma'), ('agency', 'Agência'), ('user', 'Usuário')], default='user', max_length=10)),
                ('slug', models.SlugField(blank=True, default='', max_length=60)),
                ('brand_name', models.CharField(blank=True, default='', max_length=120)),
                ('brand_color', models.CharField(blank=True, default='', max_length=7)),
                ('logo_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
