# Generated by Django 6.0.7 on 2026-07-13 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('domain', models.CharField(blank=True, max_length=200, verbose_name='Domínio')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='Segmento')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Funcionários')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefone')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('qualificado', 'Qualificado'), ('cliente', 'Cliente'), ('inativo', 'Inativo')], default='lead', max_length=20, verbose_name='Estágio')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company', verbose_name='Empresa')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('stage', models.CharField(choices=[('novo', 'Novo'), ('qualificado', 'Qualificado'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Estágio')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('expected_close', models.DateField(blank=True, null=True, verbose_name='Previsão de fechamento')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.company', verbose_name='Empresa')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.contact', verbose_name='Contato')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('task', 'Tarefa')], default='note', max_length=10, verbose_name='Tipo')),
                ('body', models.TextField(verbose_name='Conteúdo')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('done', models.BooleanField(default=False, verbose_name='Concluída')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.workspace')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.company', verbose_name='Empresa')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact', verbose_name='Contato')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.deal', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['done', '-created_at'],
            },
        ),
    ]
