# Generated by Django 6.0.7 on 2026-07-14 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_parent_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
        migrations.AddField(
            model_name='deal',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_deals', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
