# Generated by Django 6.0.7 on 2026-07-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_custom_contact_custom_deal_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('automation', 'Automação')], default='manual', max_length=12),
        ),
    ]
