# Generated by Django 6.0.7 on 2026-07-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_automation_canvas'),
        ('crm', '0003_activity_mentions_company_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='stage_kind',
            field=models.CharField(default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='crm.pipeline', verbose_name='Pipeline'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=60, verbose_name='Nome')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='Cor')),
                ('kind', models.CharField(choices=[('open', 'Aberta'), ('won', 'Ganho'), ('lost', 'Perdido')], default='open', max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveIntegerField(default=0)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['order', 'id'],
                'unique_together': {('pipeline', 'key')},
            },
        ),
    ]
