# Generated by Codex on 2026-07-15

import modules.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_deal_stage_kind_pipeline_deal_pipeline_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="card_fields",
            field=models.JSONField(
                blank=True,
                default=modules.crm.models.default_stage_card_fields,
            ),
        ),
    ]
