# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_stage_card_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address_street",
            field=models.CharField(blank=True, max_length=180, verbose_name="Endereço"),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="Número"),
        ),
        migrations.AddField(
            model_name="contact",
            name="address_complement",
            field=models.CharField(blank=True, max_length=80, verbose_name="Complemento"),
        ),
        migrations.AddField(
            model_name="contact",
            name="district",
            field=models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="contact",
            name="state",
            field=models.CharField(blank=True, max_length=2, verbose_name="UF"),
        ),
        migrations.AddField(
            model_name="contact",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20, verbose_name="CEP"),
        ),
    ]
