# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_contact_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="stage_kind",
            field=models.CharField(default="open", max_length=20),
        ),
        migrations.AlterField(
            model_name="stage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open", "Em andamento"),
                    ("won", "Ganho"),
                    ("lost", "Perdido"),
                    ("disqualified", "Desqualificado"),
                ],
                default="open",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
