# Generated by Django 6.0.6 on 2026-07-22 18:30

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_event_source_key_event_unique_event_source_key'),
        ('crm', '0007_alter_stage_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.CharField(max_length=80)),
                ('remote_jid', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('archived', 'Arquivada')], default='open', max_length=12)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message', models.CharField(blank=True, max_length=300)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Conversa do WhatsApp',
                'verbose_name_plural': 'Conversas do WhatsApp',
                'ordering': ['-last_message_at', '-updated_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.CharField(max_length=80)),
                ('provider_message_id', models.CharField(max_length=180)),
                ('direction', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Enviada')], max_length=10)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=700)),
                ('status', models.CharField(default='received', max_length=30)),
                ('sent_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.whatsappconversation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Mensagem do WhatsApp',
                'verbose_name_plural': 'Mensagens do WhatsApp',
                'ordering': ['sent_at', 'id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['workspace', '-last_message_at'], name='crm_whatsap_workspa_e0715c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['workspace', 'phone'], name='crm_whatsap_workspa_692945_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappconversation',
            unique_together={('workspace', 'instance_id', 'remote_jid')},
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='crm_whatsap_convers_2e670e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappmessage',
            unique_together={('workspace', 'instance_id', 'provider_message_id')},
        ),
    ]
