# Generated by Django 6.0.7 on 2026-07-24 03:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_workspace_dashboard_layout'),
        ('crm', '0009_whatsappconversation_is_history_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=180)),
                ('action', models.CharField(choices=[('view', 'Visualizou'), ('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('export', 'Exportou'), ('login', 'Entrou'), ('logout', 'Saiu'), ('login_failed', 'Falha de login')], max_length=16, verbose_name='Ação')),
                ('object_type', models.CharField(blank=True, max_length=40)),
                ('object_id', models.CharField(blank=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Registros de auditoria',
                'ordering': ['-created_at'],
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='crm_auditlo_workspa_ba4a95_idx'), models.Index(fields=['object_type', 'object_id'], name='crm_auditlo_object__e64726_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
