# Generated by Django 6.0.7 on 2026-07-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consentido em'),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_basis',
            field=models.CharField(blank=True, choices=[('', 'Não definida'), ('consentimento', 'Consentimento'), ('legitimo_interesse', 'Legítimo interesse'), ('contrato', 'Execução de contrato'), ('obrigacao_legal', 'Obrigação legal')], default='', max_length=20, verbose_name='Base legal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_source',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='Origem do consentimento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_status',
            field=models.CharField(choices=[('unknown', 'Não informado'), ('granted', 'Consentido'), ('withdrawn', 'Revogado')], default='unknown', max_length=12, verbose_name='Consentimento'),
        ),
        migrations.AddField(
            model_name='contact',
            name='is_anonymized',
            field=models.BooleanField(default=False, verbose_name='Anonimizado'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizou'), ('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('anonymize', 'Anonimizou'), ('consent', 'Consentimento'), ('export', 'Exportou'), ('login', 'Entrou'), ('logout', 'Saiu'), ('login_failed', 'Falha de login')], max_length=16, verbose_name='Ação'),
        ),
    ]
