# Generated by Django 6.0.7 on 2026-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contact_anonymized_at_contact_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Visualizou'), ('create', 'Criou'), ('update', 'Atualizou'), ('delete', 'Excluiu'), ('anonymize', 'Anonimizou'), ('consent', 'Consentimento'), ('access', 'Acessou (gestor)'), ('export', 'Exportou'), ('login', 'Entrou'), ('logout', 'Saiu'), ('login_failed', 'Falha de login')], max_length=16, verbose_name='Ação'),
        ),
    ]
