# Generated by Django 6.0.7 on 2026-07-26 14:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workspace_agency_workspace_suspended_and_more'),
        ('crm', '0012_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('object_type', models.CharField(choices=[('deal', 'Negócios'), ('contact', 'Contatos'), ('company', 'Empresas'), ('task', 'Tarefas')], default='deal', max_length=12)),
                ('metric', models.CharField(choices=[('count', 'Contagem'), ('sum', 'Soma'), ('avg', 'Média')], default='count', max_length=10)),
                ('value_field', models.CharField(blank=True, default='', max_length=40)),
                ('group_by', models.CharField(blank=True, default='', max_length=40)),
                ('chart', models.CharField(choices=[('kpi', 'Número'), ('bar', 'Barras'), ('pie', 'Pizza'), ('line', 'Linha'), ('list', 'Lista')], default='kpi', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cards', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Card do painel',
                'verbose_name_plural': 'Cards do painel',
                'ordering': ['order', 'id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
