# Generated by Django 6.0.7 on 2026-07-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_dashboardcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='width',
            field=models.CharField(choices=[('normal', 'Normal'), ('full', 'Largura total')], default='normal', max_length=10),
        ),
    ]
