# Generated by Django 6.0.7 on 2026-07-27 18:50

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_workspace_agency_workspace_suspended_and_more'),
        ('crm', '0014_dashboardcard_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger')], default='instagram', max_length=16)),
                ('account_id', models.CharField(max_length=80)),
                ('sender_id', models.CharField(max_length=120)),
                ('username', models.CharField(blank=True, max_length=160)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('avatar_url', models.URLField(blank=True, max_length=700)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('archived', 'Arquivada')], default='open', max_length=12)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message', models.CharField(blank=True, max_length=300)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_conversations', to='crm.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_conversations', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Conversa social',
                'verbose_name_plural': 'Conversas sociais',
                'ordering': ['-last_message_at', '-updated_at'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='instagram', max_length=16)),
                ('provider_message_id', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('incoming', 'Recebida'), ('outgoing', 'Enviada')], max_length=10)),
                ('message_type', models.CharField(default='text', max_length=30)),
                ('text', models.TextField(blank=True)),
                ('media_url', models.URLField(blank=True, max_length=900)),
                ('sent_at', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.socialconversation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_messages', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Mensagem social',
                'verbose_name_plural': 'Mensagens sociais',
                'ordering': ['sent_at', 'id'],
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['workspace', 'channel', '-last_message_at'], name='crm_socialc_workspa_49a163_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialconversation',
            unique_together={('workspace', 'channel', 'account_id', 'sender_id')},
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='crm_socialm_convers_ce7b3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmessage',
            unique_together={('workspace', 'channel', 'provider_message_id')},
        ),
    ]
