from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("whatsapp/", views.whatsapp, name="whatsapp"),
    path("whatsapp/connect/", views.whatsapp_connect, name="whatsapp_connect"),
    path("whatsapp/status/", views.whatsapp_status, name="whatsapp_status"),
    path("whatsapp/unread-count/", views.whatsapp_unread_count_view, name="whatsapp_unread_count"),
    path("whatsapp/avatar/<int:conversation_id>/", views.whatsapp_avatar, name="whatsapp_avatar"),
    path("whatsapp/conversations/<int:conversation_id>/crm/", views.whatsapp_promote_drawer, name="whatsapp_promote_drawer"),
    path("whatsapp/promote/", views.whatsapp_promote, name="whatsapp_promote"),
    path("whatsapp/sync-contacts/", views.whatsapp_sync_contacts, name="whatsapp_sync_contacts"),
    path("whatsapp/disconnect/", views.whatsapp_disconnect, name="whatsapp_disconnect"),
    path("whatsapp/send/", views.whatsapp_send, name="whatsapp_send"),
    path("workspaces/new/", views.workspace_new, name="workspace_new"),
    path("workspaces/<int:pk>/switch/", views.workspace_switch, name="workspace_switch"),
    # Platform admin console
    path("console/", views.admin_console, name="admin_console"),
    path("console/workspace/<int:pk>/suspend/", views.console_workspace_suspend, name="console_workspace_suspend"),
    path("console/workspace/<int:pk>/agency/", views.console_workspace_agency, name="console_workspace_agency"),
    path("console/workspace/<int:pk>/delete/", views.console_workspace_delete, name="console_workspace_delete"),
    path("console/user/add/", views.console_user_add, name="console_user_add"),
    path("console/user/<int:pk>/type/", views.console_user_type, name="console_user_type"),
    # Agency console
    path("agencia/", views.agency_console, name="agency_console"),
    path("agencia/novo-cliente/", views.client_onboarding, name="client_onboarding"),
    path("agencia/marca/", views.agency_branding, name="agency_branding"),
    # Onboarding wizards
    path("console/nova-agencia/", views.agency_onboarding, name="agency_onboarding"),
    path("onboarding/pronto/", views.onboarding_done, name="onboarding_done"),
    # White-label login for an agency's clients
    path("e/<slug:slug>/", views.agency_login, name="agency_login"),
    # Google OAuth login
    path("accounts/google/login/", views.google_login, name="google_login"),
    path("accounts/google/callback/", views.google_callback, name="google_callback"),
    path("settings/", views.settings_hub, name="settings"),
    path("settings/members/", views.members, name="members"),
    path("settings/members/add/", views.member_add, name="member_add"),
    path("settings/members/<int:pk>/role/", views.member_update, name="member_update"),
    path("settings/members/<int:pk>/remove/", views.member_remove, name="member_remove"),
    path("settings/fields/", views.custom_fields, name="custom_fields"),
    path("settings/fields/<str:object_type>/", views.custom_fields_object, name="custom_fields_object"),
    path("settings/fields/add/", views.custom_field_add, name="custom_field_add"),
    path("settings/fields/<int:pk>/edit/", views.custom_field_update, name="custom_field_update"),
    path("settings/fields/<int:pk>/delete/", views.custom_field_delete, name="custom_field_delete"),
    path("settings/automations/", views.automations, name="automations"),
    path("settings/automations/new/", views.automation_editor, name="automation_new"),
    path("settings/automations/<int:pk>/edit/", views.automation_editor, name="automation_edit"),
    path("settings/automations/add/", views.automation_add, name="automation_add"),
    path("settings/automations/<int:pk>/toggle/", views.automation_toggle, name="automation_toggle"),
    path("settings/automations/<int:pk>/delete/", views.automation_delete, name="automation_delete"),
    path("settings/integrations/", views.integrations, name="integrations"),
    path("settings/integrations/connect/", views.integration_connect, name="integration_connect"),
    path("settings/integrations/disconnect/", views.integration_disconnect, name="integration_disconnect"),
    path("settings/integrations/facebook/connect/", views.facebook_connect, name="facebook_connect"),
    path("settings/integrations/facebook/callback/", views.facebook_callback, name="facebook_callback"),
    path("settings/integrations/facebook/page/", views.facebook_select_page, name="facebook_select_page"),
    path("settings/integrations/facebook/page/switch/", views.facebook_switch_page, name="facebook_switch_page"),
    path("settings/integrations/facebook/forms/", views.facebook_forms, name="facebook_forms"),
    path("settings/integrations/facebook/forms/sync/", views.facebook_sync_forms, name="facebook_sync_forms"),
    path("settings/integrations/facebook/forms/<str:form_id>/map/", views.facebook_form_map, name="facebook_form_map"),
    path("settings/integrations/facebook/forms/<str:form_id>/toggle/", views.facebook_form_toggle, name="facebook_form_toggle"),
    path("webhooks/automation/<str:key>/", views.automation_webhook, name="automation_webhook"),
    path("webhooks/facebook/leadgen/", views.facebook_leadgen, name="facebook_leadgen"),
    path("webhooks/whatsapp/<str:secret>/", views.whatsapp_webhook, name="whatsapp_webhook"),
    path("settings/appearance/", views.appearance, name="appearance"),
    path("settings/dashboard/", views.dashboard_settings, name="dashboard_settings"),
    path("dashboard/customize/", views.dashboard_customize, name="dashboard_customize"),
    path("dashboard/cards/new/", views.dashboard_card_form, name="dashboard_card_new"),
    path("dashboard/cards/<int:pk>/edit/", views.dashboard_card_form, name="dashboard_card_edit"),
    path("dashboard/cards/<int:pk>/delete/", views.dashboard_card_delete, name="dashboard_card_delete"),
    path("dashboard/cards/preview/", views.dashboard_card_preview, name="dashboard_card_preview"),
    path("settings/audit/", views.audit_log, name="audit_log"),
    path("settings/privacy/", views.privacy_settings, name="privacy_settings"),
]
